### ISSUE TITLE
After pod update receiving "No such file or directory error"

### ISSUE THREAD

**Issue by ashvar** [FredericJacobs/OpenSSL-Pod#12]
Keep receiving the following error log after `pod install`:

```
-> Installing OpenSSL (1.0.201)
  > Copying OpenSSL from `/Users/ashotvardanian/Library/Caches/CocoaPods/Pods/Release/OpenSSL/1.0.201-4e990` to `Pods/OpenSSL`
 > Running prepare command
   $ /bin/bash -c ' 'set\ -e' 'VERSION\=\"1.0.2a\"' 'SDKVERSION\=\`xcrun\ --sdk\ iphoneos\ --show-sdk-version\ 2\>\ /dev/null\`' '' 'BASEPATH\=\"\$\{PWD\}\"'
   'CURRENTPATH\=\"/tmp/openssl\"' 'ARCHS\=\"i386\ x86_64\ armv7\ armv7s\ arm64\"' 'DEVELOPER\=\`xcode-select\ -print-path\`' '' 'mkdir\ -p\
   \"\$\{CURRENTPATH\}\"' 'mkdir\ -p\ \"\$\{CURRENTPATH\}/bin\"' '' 'cp\ \"file.tgz\"\ \"\$\{CURRENTPATH\}/file.tgz\"' 'cd\ \"\$\{CURRENTPATH\}\"' 'tar\ -xzf\
   file.tgz' 'cd\ \"openssl-\$\{VERSION\}\"' '' 'for\ ARCH\ in\ \$\{ARCHS\}' 'do' '\ \ CONFIGURE_FOR\=\"iphoneos-cross\"' '' '\ \ if\ \[\ \"\$\{ARCH\}\"\ \=\=\
   \"i386\"\ \]\ \|\|\ \[\ \"\$\{ARCH\}\"\ \=\=\ \"x86_64\"\ \]\ \;' '\ \ then' '\ \ \ \ PLATFORM\=\"iPhoneSimulator\"' '\ \ \ \ if\ \[\ \"\$\{ARCH\}\"\ \=\=\
   \"x86_64\"\ \]\ \;' '\ \ \ \ then' '\ \ \ \ \ \ CONFIGURE_FOR\=\"darwin64-x86_64-cc\"' '\ \ \ \ fi' '\ \ else' '\ \ \ \ sed\ -ie\ \"s\!static\ volatile\
   sig_atomic_t\ intr_signal\;\!static\ volatile\ intr_signal\;\!\"\ \"crypto/ui/ui_openssl.c\"' '\ \ \ \ PLATFORM\=\"iPhoneOS\"' '\ \ fi' '' '\ \ export\
   CROSS_TOP\=\"\$\{DEVELOPER\}/Platforms/\$\{PLATFORM\}.platform/Developer\"' '\ \ export\ CROSS_SDK\=\"\$\{PLATFORM\}\$\{SDKVERSION\}.sdk\"' '' '\ \ echo\
   \"Building\ openssl-\$\{VERSION\}\ for\ \$\{PLATFORM\}\ \$\{SDKVERSION\}\ \$\{ARCH\}\"' '\ \ echo\ \"Please\ stand\ by...\"' '' '\ \ export\
   CC\=\"\$\{DEVELOPER\}/usr/bin/gcc\ -arch\ \$\{ARCH\}\ -miphoneos-version-min\=\$\{SDKVERSION\}\"' '\ \ mkdir\ -p\
   \"\$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk\"' '\ \
   LOG\=\"\$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk/build-openssl-\$\{VERSION\}.log\"' '' '\ \ LIPO_LIBSSL\=\"\$\{LIPO_LIBSSL\}\
   \$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk/lib/libssl.a\"' '\ \ LIPO_LIBCRYPTO\=\"\$\{LIPO_LIBCRYPTO\}\
   \$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk/lib/libcrypto.a\"' '' '\ \ ./Configure\ \$\{CONFIGURE_FOR\}\
   --openssldir\=\"\$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk\"\ \>\ \"\$\{LOG\}\"\ 2\>\&1' '\ \ sed\ -ie\
   \"s\!\^CFLAG\=\!CFLAG\=-isysroot\ \$\{CROSS_TOP\}/SDKs/\$\{CROSS_SDK\}\ \!\"\ \"Makefile\"' '' '\ \ make\ \>\>\ \"\$\{LOG\}\"\ 2\>\&1' '\ \ make\ all\
   install_sw\ \>\>\ \"\$\{LOG\}\"\ 2\>\&1' '\ \ make\ clean\ \>\>\ \"\$\{LOG\}\"\ 2\>\&1' 'done' '' '' 'echo\ \"Build\ library...\"' 'rm\ -rf\
   \"\$\{BASEPATH\}/lib/\"' 'mkdir\ -p\ \"\$\{BASEPATH\}/lib/\"' 'lipo\ -create\ \$\{LIPO_LIBSSL\}\ \ \ \ -output\ \"\$\{BASEPATH\}/lib/libssl.a\"' 'lipo\
   -create\ \$\{LIPO_LIBCRYPTO\}\ -output\ \"\$\{BASEPATH\}/lib/libcrypto.a\"' '' 'echo\ \"Copying\ headers...\"' 'rm\ -rf\
   \"\$\{BASEPATH\}/opensslIncludes/\"' 'mkdir\ -p\ \"\$\{BASEPATH\}/opensslIncludes/\"' 'cp\ -RL\ \"\$\{CURRENTPATH\}/openssl-\$\{VERSION\}/include/openssl\"\
   \"\$\{BASEPATH\}/opensslIncludes/\"' '' 'cd\ \"\$\{BASEPATH\}\"' 'echo\ \"Building\ done.\"' '' 'echo\ \"Cleaning\ up...\"' 'rm\ -rf\ \"\$\{CURRENTPATH\}\"'
   'echo\ \"Done.\"
   cp: file.tgz: No such file or directory

[!] /bin/bash -c '
'set\ -e'
'VERSION\=\"1.0.2a\"'
'SDKVERSION\=\`xcrun\ --sdk\ iphoneos\ --show-sdk-version\ 2\>\ /dev/null\`'
''
'BASEPATH\=\"\$\{PWD\}\"'
'CURRENTPATH\=\"/tmp/openssl\"'
'ARCHS\=\"i386\ x86_64\ armv7\ armv7s\ arm64\"'
'DEVELOPER\=\`xcode-select\ -print-path\`'
''
'mkdir\ -p\ \"\$\{CURRENTPATH\}\"'
'mkdir\ -p\ \"\$\{CURRENTPATH\}/bin\"'
''
'cp\ \"file.tgz\"\ \"\$\{CURRENTPATH\}/file.tgz\"'
'cd\ \"\$\{CURRENTPATH\}\"'
'tar\ -xzf\ file.tgz'
'cd\ \"openssl-\$\{VERSION\}\"'
''
'for\ ARCH\ in\ \$\{ARCHS\}'
'do'
'\ \ CONFIGURE_FOR\=\"iphoneos-cross\"'
''
'\ \ if\ \[\ \"\$\{ARCH\}\"\ \=\=\ \"i386\"\ \]\ \|\|\ \[\ \"\$\{ARCH\}\"\ \=\=\ \"x86_64\"\ \]\ \;'
'\ \ then'
'\ \ \ \ PLATFORM\=\"iPhoneSimulator\"'
'\ \ \ \ if\ \[\ \"\$\{ARCH\}\"\ \=\=\ \"x86_64\"\ \]\ \;'
'\ \ \ \ then'
'\ \ \ \ \ \ CONFIGURE_FOR\=\"darwin64-x86_64-cc\"'
'\ \ \ \ fi'
'\ \ else'
'\ \ \ \ sed\ -ie\ \"s\!static\ volatile\ sig_atomic_t\ intr_signal\;\!static\ volatile\ intr_signal\;\!\"\ \"crypto/ui/ui_openssl.c\"'
'\ \ \ \ PLATFORM\=\"iPhoneOS\"'
'\ \ fi'
''
'\ \ export\ CROSS_TOP\=\"\$\{DEVELOPER\}/Platforms/\$\{PLATFORM\}.platform/Developer\"'
'\ \ export\ CROSS_SDK\=\"\$\{PLATFORM\}\$\{SDKVERSION\}.sdk\"'
''
'\ \ echo\ \"Building\ openssl-\$\{VERSION\}\ for\ \$\{PLATFORM\}\ \$\{SDKVERSION\}\ \$\{ARCH\}\"'
'\ \ echo\ \"Please\ stand\ by...\"'
''
'\ \ export\ CC\=\"\$\{DEVELOPER\}/usr/bin/gcc\ -arch\ \$\{ARCH\}\ -miphoneos-version-min\=\$\{SDKVERSION\}\"'
'\ \ mkdir\ -p\ \"\$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk\"'
'\ \ LOG\=\"\$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk/build-openssl-\$\{VERSION\}.log\"'
''
'\ \ LIPO_LIBSSL\=\"\$\{LIPO_LIBSSL\}\ \$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk/lib/libssl.a\"'
'\ \ LIPO_LIBCRYPTO\=\"\$\{LIPO_LIBCRYPTO\}\ \$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk/lib/libcrypto.a\"'
''
'\ \ ./Configure\ \$\{CONFIGURE_FOR\}\ --openssldir\=\"\$\{CURRENTPATH\}/bin/\$\{PLATFORM\}\$\{SDKVERSION\}-\$\{ARCH\}.sdk\"\ \>\ \"\$\{LOG\}\"\ 2\>\&1'
'\ \ sed\ -ie\ \"s\!\^CFLAG\=\!CFLAG\=-isysroot\ \$\{CROSS_TOP\}/SDKs/\$\{CROSS_SDK\}\ \!\"\ \"Makefile\"'
''
'\ \ make\ \>\>\ \"\$\{LOG\}\"\ 2\>\&1'
'\ \ make\ all\ install_sw\ \>\>\ \"\$\{LOG\}\"\ 2\>\&1'
'\ \ make\ clean\ \>\>\ \"\$\{LOG\}\"\ 2\>\&1'
'done'
''
''
'echo\ \"Build\ library...\"'
'rm\ -rf\ \"\$\{BASEPATH\}/lib/\"'
'mkdir\ -p\ \"\$\{BASEPATH\}/lib/\"'
'lipo\ -create\ \$\{LIPO_LIBSSL\}\ \ \ \ -output\ \"\$\{BASEPATH\}/lib/libssl.a\"'
'lipo\ -create\ \$\{LIPO_LIBCRYPTO\}\ -output\ \"\$\{BASEPATH\}/lib/libcrypto.a\"'
''
'echo\ \"Copying\ headers...\"'
'rm\ -rf\ \"\$\{BASEPATH\}/opensslIncludes/\"'
'mkdir\ -p\ \"\$\{BASEPATH\}/opensslIncludes/\"'
'cp\ -RL\ \"\$\{CURRENTPATH\}/openssl-\$\{VERSION\}/include/openssl\"\ \"\$\{BASEPATH\}/opensslIncludes/\"'
''
'cd\ \"\$\{BASEPATH\}\"'
'echo\ \"Building\ done.\"'
''
'echo\ \"Cleaning\ up...\"'
'rm\ -rf\ \"\$\{CURRENTPATH\}\"'
'echo\ \"Done.\"

cp: file.tgz: No such file or directory


/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/executable.rb:72:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/pod_source_installer.rb:110:in `block (2 levels) in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/pod_source_installer.rb:106:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/pod_source_installer.rb:106:in `block in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/pod_source_installer.rb:105:in `run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer/pod_source_installer.rb:46:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:303:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:278:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:277:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:269:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:269:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:121:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:119:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/installer.rb:91:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0.beta.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```
What to do with that?

**Comment by FredericJacobs** [comment]
It's an issue with the 0.37.0 beta version. I only support the pod on stable. I don't know if they are planning to going to remove the `file.tgz` file or not.
